Sprint2/step2
wood-stock/react-burger pull request #5
Opened 2021-06-27 20:42 UTC by wood-stock

Здравствуйте, извините что проект не причесан, увлекся пытаясь решить вопрос сортировки и попал в дедлайн (проблема осталась) очень не хочу из-за одного элемента уходить в академ.

2021-06-28 17:47 UTC, SmilingJey requested changes
Здравствуйте!

Неплохая работа работа. Стейт перенесен в redux, правильно работает добавление ингредиентов перетаскиванием

Но есть несколько замечаний:

**Замечания которые необходимо исправить:**

- разделите редьюсер на небольшие редьюсеры обрабатывающие данные одной предметной области

- проблему с сортировкой нужно исправить, начните с исправления замечания по key элементов конструктора 

- перенесите логику рассчета полной стоимости просто в компонент, не нужно её выносить в редьюсер

- в асинхронных экшенах есть замечания по диспатчу ошибок и экшена

- лишний файл add-ingredient copy.jsx

**Места, в которых можно улучшить проект:**

- рассчеты в компонентах оберните  в useMemo, что бы он срабатывали только при изменении данных, а не при каждом рендере

- из асинзронных экшенов возвращать промис

Подробнее замечания описаны ниже в комментариях к самим участкам кода:

2021-06-28 17:47 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +      type: RECALCULATE_TOTAL_PRICE,
**Надо исправить**

полная стоимость это производные данные от даннных конструктора и достаточног просто вычислить в самом компоненте используя useMemo

```
const totalPrice = useMome(()=> {
  рассчет полной стоимости
}, [constructorBun, constructorIngredients])
```

2021-06-28 17:47 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +  const idForOrder = [
**Можно лучше**

не нужно вычислять массив при каждом рендере, вычисляйте массив только при отправке

2021-06-28 17:47 UTC, SmilingJey commented on src/components/burger-ingredient/burger-ingredient.jsx
> +  const count = [
**Можно лучше**

оберните этот рассчет в useMemo, что бы он срабатывал только при изменении данных, а не при каждом рендере

2021-06-28 17:47 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.jsx
> +              key={Math.round(Math.random() * 1000)}
**Надо исправаить**

из за того что для key каждый раз генерируется новое значение как раз и могут происходить проблемы с сортировкой перетаскивание т.к. вызывается постоянный перерендер элементов даже если они не изменяются во время перетаскивания

Генерируйте уникальный id при добавлении ингредиента в конструктор и используйте его

2021-06-28 17:47 UTC, SmilingJey commented on src/services/reducers/ingredients.js
> +export const ingredientsReducer = (state = initialState, action) => {
**Надо исправить**

разделите редьюсер на небольшие редьюсеры обрабатывающие данные одной предметной области (одного "домена"), например
- редьюсер хранения загруженных ингредиентов
- редьюсер попапов
- редьюсер конструктора
- редьюсер оформления заказа

Файловая структура может выглядеть примерно так:
![Screenshot_14](https://user-images.githubusercontent.com/9317133/123677664-110c4e80-d84e-11eb-9510-1d277877e262.png)


Экшены и редьюсер обрабатывающий соответвующие экшены лежат в своих папках

2021-06-28 17:47 UTC, SmilingJey commented on src/services/actions/ingredients.js
> +          type: GET_INGREDIENTS_ERROR,
**Надо исправить**

здесь нужно не делать диспатч, а вернуть отклоненный промис и про этом попадем в catch, где уже будет выполняться диспатч

2021-06-28 17:47 UTC, SmilingJey commented on src/services/actions/ingredients.js
> +    .catch((error) => console.log('error', error));
**Надо исправить**

при ошибке должен диспатчится ADD_ORDER_FAILED

2021-06-28 17:47 UTC, SmilingJey commented on src/services/actions/ingredients.js
> +  fetch(oredersApi, {
**Надо исправить**

перед запросом нужно диспатчить ADD_ORDER

2021-06-28 17:47 UTC, SmilingJey commented on src/services/actions/ingredients.js
> +  fetch(ingredientsApi)
**Можно лучше**

следует делать return промиса, что нам поможет при тестировании в следующем спринте и при необходимости можно будет продолжить цепочку в компоненте и совершить дествие после выполнения запроса

т.е. должно быть:
```
export const getIngredients = () => (dispatch) => {
  dispatch({
    type: GET_INGREDIENTS,
  });
  return fetch(ingredientsApi)
        .................
```

проверьте и других похожих местах

2021-06-28 17:47 UTC, SmilingJey commented on src/services/reducers/ingredients.js
> +    case RECALCULATE_TOTAL_PRICE: {
**Нажо исправить**

не нужно делать вычисления цены в редьюсере, перенесите просто в компонент

2021-06-28 17:47 UTC, SmilingJey commented on src/services/reducers/ingredients.js
> +        constructorBun: { ...action.ingredients[1] },
**Можно лучше**

по заданию не подразумевается, что сразу добавляется булка, конструктор должен быть пустой

2021-06-28 17:47 UTC, SmilingJey commented on src/components/constructor-ingredient/add-ingredient copy.jsx
> +
**Надо исправить**

файл add-ingredient copy.jsx явно лишний

2021-06-29 12:39 UTC, wood-stock commented
Большое спасибо за ревью

2021-06-29 20:56 UTC, SmilingJey approved these changes
Отлично, критиеские замечания исправлены, теперь сортировка работает верно

Но не забудьте поправить отмеченное ниже замечание и генерировать ключ не в рельюсере, а при создании экшена, иначе вы столкнетесь с проблемой при тестировании редьюсера в 3 спринте

Так же уберите обводку вокруг содержимого бургера, это не по макету
![Screenshot_62](https://user-images.githubusercontent.com/9317133/123866277-81da6600-d935-11eb-9b3a-a398318fa734.png)

Успехов в дальнейшем обучении!

2021-06-29 20:56 UTC, SmilingJey commented on src/services/reducers/constructor.js
> +              key: Math.round(Math.random() * 1000),
**Надо исправаить**

редьюсер должен быть чистой функцией, а сейчас key гененрируется внутри редьюсера случайно, это делает редьюсер не читсой функцией

Нужно генерировать ключ при создании экшена и помещать ключ в payload и уже в редьюсере просто брать из payload

2021-06-29 20:56 UTC, SmilingJey commented on src/services/reducers/constructor.js
> +              key: Math.round(Math.random() * 1000),
**Надо исправаить**

редьюсер должен быть чистой функцией

2021-06-30 06:58 UTC, wood-stock commented on src/services/reducers/constructor.js
> +              key: Math.round(Math.random() * 1000),
Юху!!! спасибо!

2021-06-30 19:33 UTC, merged